### ISSUE TITLE
Doesn't open all .html files

### ISSUE THREAD

**Issue by Appelmoes1337** [fabiospampinato/vscode-open-multiple-files#10]
When I try to run the plugin it doesn't open all the .html files but only certain files. I set the maximum to 100,000 but it doesn't work.

**Comment by fabiospampinato** [comment]
It seems to work for me strangely 🤔 Can you provide more info? Like a screen recording of what's happening exactly?

**Comment by fabiospampinato** [comment]
Closing for lack of additional info.
