### ISSUE TITLE
Notify when the number of files matched by the glob pattern exceeds the open limit

### ISSUE THREAD

**Issue by hugoalh** [fabiospampinato/vscode-open-multiple-files#11]
When the number of files matched by the glob pattern exceeds the open limit, there haven't any notifications or alerts, cause easily unaware some of the files have not been opened due to this open limit. It would be helpful if the extension could provide some form of notification about this issue.

**Comment by fabiospampinato** [comment]
Implemented in v2, thanks for the feedback 👍

<img width="488" alt="Screen Shot 2024-03-08 at 19 12 31" src="https://github.com/fabiospampinato/vscode-open-multiple-files/assets/1812093/bea6ed4a-3853-46d5-b481-590bd2f2421a">
