### ISSUE TITLE
Version 2.0.0 doesn't open files in new tabs

### ISSUE THREAD

**Issue by brainz80** [fabiospampinato/vscode-open-multiple-files#12]
When running `Open Multiple Files` against glob `src/**/*.ts` instead of opening each file in its own tab; 2.0.0 opens a single tab and flashes though all files in it.

**Comment by fabiospampinato** [comment]
Well spotted, I didn't remember why the code that opened files looked like that, and I have temporary tabs turned off at the app level so I didn't spot this issue, I'll get this fixed, possibly later today or tomorrow 👍

**Comment by fabiospampinato** [comment]
Fixed in v2.0.1, thanks.
