### ISSUE TITLE
Doesn't work from context menu

### ISSUE THREAD

**Issue by usernamehw** [fabiospampinato/vscode-open-multiple-files#2]
Having a directory:
```
C:.
└───src
    │   2.ts
    │
    └───Components
        │   1.ts
        │
        └───Something
                something.ts
```
![ex](https://user-images.githubusercontent.com/9638156/49943631-78b15700-fef9-11e8-8df1-1a8beba3dbd6.png)
Using context menu on `src` folder in the file explorer => `**/*` => opens only one file **1.ts**

**Comment by fabiospampinato** [comment]
Just tried with the same folder structure and it works for me 🤔

Can you give me some more details such as: OS version, VSC version, extension version?

**Comment by usernamehw** [comment]
```
Version: 1.31.0-insider (user setup)
Commit: 7ab53e6d1c7998006bc70f18230178a702598222
Date: 2018-12-13T06:20:30.449Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by fabiospampinato** [comment]
Are you using the latest version of the extension?

Can you check if the problem reproduces in non-insiders VSC?

**Comment by usernamehw** [comment]
Latest. It does (Stable and Exploration).

**Comment by fabiospampinato** [comment]
You mentioned "Doesn't work **from context menu**", does it work from the command palette?

**Comment by usernamehw** [comment]
Yes.

**Comment by fabiospampinato** [comment]
Very strange 🤔

**Comment by fabiospampinato** [comment]
Are you using this in a multi-root workspace?

**Comment by usernamehw** [comment]
No.

**Comment by usernamehw** [comment]
Maybe Windows-specific bug or a new vscode version bug?

**Comment by fabiospampinato** [comment]
Probably, I haven't updated to v1.30 yet.

I don't have time for this today, but I'll try to get it fixed as soon as I can.

**Comment by usernamehw** [comment]
As far as I can understand the reason is that `includeGlob` is somehow not normalized:

From command palette: `src/**/*` - works
From context menu: `src\**\*` - doesn't work

**Comment by usernamehw** [comment]
Changing
```typescript
includeGlob = path.join ( relPath, includeGlob )
```
to
```typescript
includeGlob = path.join ( relPath, includeGlob ).replace (/\\/g, '/' );
```
fixes it. 
But I don't know if it has any side effects. Maybe checking if OS is Windows first would help?

**Comment by fabiospampinato** [comment]
> From command palette: src/**/* - works
> From context menu: src\**\* - doesn't work

Really? That's very strange, we are using the same one regardless of where the action started from:

https://github.com/fabiospampinato/vscode-open-multiple-files/blob/2c29bdf5c7f8ad7cc55c35621862e32275a83d66/src/commands.ts#L24

Can you double check? If that value gets changed by VSC I think that's a problem we should report to them.

> But I don't know if it has any side effects. Maybe checking if OS is Windows first would help?

No need, I don't think there should be side effects 🤔

**Comment by usernamehw** [comment]
You are overwriting that variable later in code.

**Comment by fabiospampinato** [comment]
Here you mean?:

https://github.com/fabiospampinato/vscode-open-multiple-files/blob/2c29bdf5c7f8ad7cc55c35621862e32275a83d66/src/commands.ts#L41-L42

If you're using the glob `src/**/*` I wouldn't expect the forward slashes to be replaced with backwards slashes though 🤔

**Comment by usernamehw** [comment]
1. Are you testing it on Windows?
1. Are you invoking it from the context menu?

**Comment by fabiospampinato** [comment]
I haven't tested it on Windows yet. Using it both from the context menu and the command palette works for me under macOS.

**Comment by usernamehw** [comment]
My best bet is that `path.join` normalizes string and produces different result on Windows OS.

https://shapeshed.com/writing-cross-platform-node/#use-path-join-to-join-folder-names

**Comment by fabiospampinato** [comment]
That seems to be the case. I suppose your solution of replacing backwards slashes with forwards slashes should fix it then. Maybe there could be a problem with it if somewhere in `relPath` there's a directory's name which contains a backslash, but that's probably an edge case not worth supporting.

Also thanks for linking that article, it looks worthwhile to read it.
