### ISSUE TITLE
Include .gitignore patterns in excluded files

### ISSUE THREAD

**Issue by mokkabonna** [fabiospampinato/vscode-open-multiple-files#9]
Many extensions does ignore git ignored files by default. 

An option could be included to turn that on/off. IMO it should be on by default.

**Comment by fabiospampinato** [comment]
Implemented in v2.

There's a new setting, `openMultipleFiles.ignore`, which accepts an array of file names to look for, that point to .gitignore-like files. By default this array is just `[".gitignore"]`.

There is one maybe surprising detail about this: ignore files are handled kinda like they are handled by git, meaning that if you are searing inside folder "foo/bar", and there are no ".gitignore" files found inside "foo/bar", then no gitignore patters will be applied to the search, even if a ".gitignore" file exists at the root of the folder. The point about it working like this is that if it didn't work like this it would basically be impossible to explicitly search into `dist`, or whatever folder is ignored by a `.gitignore` higher up. Still, when the command this extension provides will be executed from the command palette the root `.gitignore` file will be taken into account.
